title: OTel Collector Migration Guide
description: A field guide for SREs and platform engineers migrating to the OpenTelemetry Collector
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
